### PR TITLE
Changed vis-network to hierarchical and forceAtlas2Based

### PR DESCRIPTION
**Pull request by walthowd**
Changed visualization mode to allow better visualization of the network, and specifically better visualization from coordinator to router and end devices to routers.

### CODE REVIEW

**Comment by dmulcahey** [comment]
@Adminiuga thoughts? Should we make this user configurable?

**Comment by Adminiuga** [comment]
Yes.
 For me personally atlas based layout was giving me better results.

**Comment by walthowd** [comment]
Holy cold day in hell! Dave couldn't strong arm anyone else into working on this! 😂🥳👍

**Comment by dmulcahey** [comment]
I’ll add this back in when I get time to make it selectable. Sorry for the false happiness!

**Comment by jeepotvin** [comment]
Glad I found this issue. Came across this `forceAtlas2Based` vs `barnesHut` mode on [reddit](https://www.reddit.com/r/homeassistant/comments/eszkjc/zigbee_network_mapping_with_zha_my_77_node_network/ffd6hko/?utm_source=reddit&utm_medium=web2x&context=3).

Tried to manually edit the JS file such as suggested but didn't work out as expected. Can we still apply the `forceAtlas2Based`  mode manually even if there's no user config yet? Thanks!

**Pull request merged**
